geemap.py: velocity requires xarray
xarray is not a required dependency.

```
  File "/home/runner/work/geemap/geemap/geemap/geemap.py", line 28, in <module>
    from ipyleaflet.velocity import Velocity
  File "/home/runner/work/geemap/geemap/.venv/lib/python3.10/site-packages/ipyleaflet/velocity.py", line 12, in <module>
    class Velocity(Layer):
  File "/home/runner/work/geemap/geemap/.venv/lib/python3.10/site-packages/ipyleaflet/velocity.py", line 58, in Velocity
    data = Dataset().tag(dtype=None, sync=True, to_json=ds_x_to_json)
  File "/home/runner/work/geemap/geemap/.venv/lib/python3.10/site-packages/traittypes/traittypes.py", line 265, in __init__
    import xarray as xr
ModuleNotFoundError: No module named 'xarray'
Please restart Jupyter kernel after installation if you encounter any errors when importing geemap.
Error: Process completed with exit code 1.
```